import { WeightPreset } from "./types";

export const PRESETS: WeightPreset[] = [
  {
    id: "expert",
    name: "Expert Recommended",
    description: "Practitioner-validated core criteria",
    icon: "GraduationCap",
    weights: {
      historicalPresence: 90,
      sstSuitability: 80,
      nutrientAvailability: 85,
      depthSuitability: 40,
      urchinDensityRisk: 40,
      waveExposure: 30,
      proximityToKelp: 35,
      waterClarity: 30,
      siteAccessibility: 80,
    },
  },
  {
    id: "balanced",
    name: "Balanced",
    description: "Equal weight across all metrics",
    icon: "Scale",
    weights: {
      historicalPresence: 50,
      sstSuitability: 50,
      nutrientAvailability: 50,
      depthSuitability: 50,
      urchinDensityRisk: 50,
      waveExposure: 50,
      proximityToKelp: 50,
      waterClarity: 50,
      siteAccessibility: 50,
    },
  },
  {
    id: "urchin-defense",
    name: "Urchin Defense",
    description: "Prioritize sites with low urchin barren risk",
    icon: "ShieldAlert",
    weights: {
      historicalPresence: 40,
      sstSuitability: 30,
      nutrientAvailability: 40,
      depthSuitability: 30,
      urchinDensityRisk: 100,
      waveExposure: 20,
      proximityToKelp: 60,
      waterClarity: 30,
      siteAccessibility: 50,
    },
  },
  {
    id: "historical",
    name: "Historical Recovery",
    description: "Focus on sites with proven kelp history",
    icon: "History",
    weights: {
      historicalPresence: 100,
      sstSuitability: 40,
      nutrientAvailability: 50,
      depthSuitability: 40,
      urchinDensityRisk: 50,
      waveExposure: 30,
      proximityToKelp: 80,
      waterClarity: 40,
      siteAccessibility: 45,
    },
  },
  {
    id: "optimal-conditions",
    name: "Optimal Conditions",
    description: "Prioritize current environmental suitability",
    icon: "Sparkles",
    weights: {
      historicalPresence: 30,
      sstSuitability: 90,
      nutrientAvailability: 90,
      depthSuitability: 80,
      urchinDensityRisk: 40,
      waveExposure: 60,
      proximityToKelp: 30,
      waterClarity: 80,
      siteAccessibility: 40,
    },
  },
  {
    id: "resilience",
    name: "Climate Resilience",
    description: "Sites most likely to survive warming trends",
    icon: "Thermometer",
    weights: {
      historicalPresence: 40,
      sstSuitability: 100,
      nutrientAvailability: 80,
      depthSuitability: 50,
      urchinDensityRisk: 60,
      waveExposure: 70,
      proximityToKelp: 40,
      waterClarity: 50,
      siteAccessibility: 35,
    },
  },
];

export const DEFAULT_WEIGHTS = PRESETS[0].weights;
