import { Site } from "./types";

export const SITES: Site[] = [
  // ─── NORTH COAST (Strong upwelling nutrients, cooler temps, higher wave exposure) ───
  {
    id: "shelter-cove",
    name: "Shelter Cove",
    location: "Humboldt County",
    coordinates: { lat: 40.0258, lng: -124.0733 },
    region: "North Coast",
    description:
      "Remote rocky coastline with strong upwelling and cold nutrient-rich waters. Historically supported dense bull kelp forests before the 2014 marine heatwave.",
    metrics: {
      historicalPresence: 78,
      sstSuitability: 72,
      nutrientAvailability: 94,
      depthSuitability: 68,
      urchinDensityRisk: 35,
      waveExposure: 42,
      proximityToKelp: 55,
      waterClarity: 65,
      siteAccessibility: 30,
    },
    riskFlags: [
      { type: "high", label: "Severe urchin barrens" },
      { type: "medium", label: "High wave exposure" },
      { type: "high", label: "Remote — limited boat access" },
    ],
  },
  {
    id: "fort-bragg",
    name: "Fort Bragg - Noyo Bay",
    location: "Mendocino County",
    coordinates: { lat: 39.4457, lng: -123.8053 },
    region: "North Coast",
    description:
      "Active fishing port with adjacent rocky reefs. Bull kelp historically dominated but experienced >90% loss post-2014.",
    metrics: {
      historicalPresence: 85,
      sstSuitability: 74,
      nutrientAvailability: 88,
      depthSuitability: 72,
      urchinDensityRisk: 40,
      waveExposure: 48,
      proximityToKelp: 62,
      waterClarity: 70,
      siteAccessibility: 72,
    },
    riskFlags: [
      { type: "high", label: "Urchin barren encroachment" },
    ],
  },
  {
    id: "point-arena",
    name: "Point Arena Cove",
    location: "Mendocino County",
    coordinates: { lat: 38.9085, lng: -123.7076 },
    region: "North Coast",
    description:
      "Protected cove with historical giant kelp presence and strong upwelling nutrients. Active urchin removal efforts underway.",
    metrics: {
      historicalPresence: 82,
      sstSuitability: 76,
      nutrientAvailability: 91,
      depthSuitability: 75,
      urchinDensityRisk: 58,
      waveExposure: 62,
      proximityToKelp: 72,
      waterClarity: 71,
      siteAccessibility: 65,
    },
    riskFlags: [
      { type: "medium", label: "Moderate urchin pressure" },
    ],
  },
  {
    id: "salt-point",
    name: "Salt Point State Park",
    location: "Sonoma County",
    coordinates: { lat: 38.5654, lng: -123.3301 },
    region: "North Coast",
    description:
      "Marine protected area with sandstone and mudstone reefs. Once hosted extensive bull kelp canopies visible from shore.",
    metrics: {
      historicalPresence: 88,
      sstSuitability: 75,
      nutrientAvailability: 86,
      depthSuitability: 70,
      urchinDensityRisk: 42,
      waveExposure: 55,
      proximityToKelp: 58,
      waterClarity: 68,
      siteAccessibility: 55,
    },
    riskFlags: [
      { type: "high", label: "Dense urchin barrens" },
      { type: "low", label: "MPA protections in place" },
    ],
  },
  {
    id: "bodega-bay",
    name: "Bodega Bay - Horseshoe Cove",
    location: "Sonoma County",
    coordinates: { lat: 38.3132, lng: -123.0710 },
    region: "North Coast",
    description:
      "Adjacent to UC Davis Bodega Marine Laboratory. Strong research infrastructure supports monitoring and restoration efforts.",
    metrics: {
      historicalPresence: 74,
      sstSuitability: 70,
      nutrientAvailability: 82,
      depthSuitability: 78,
      urchinDensityRisk: 52,
      waveExposure: 68,
      proximityToKelp: 65,
      waterClarity: 73,
      siteAccessibility: 88,
    },
    riskFlags: [
      { type: "medium", label: "Moderate urchin density" },
    ],
  },

  // ─── CENTRAL COAST (Excellent historical presence, variable urchin pressure) ───
  {  
    id: "pacific-grove",
    name: "Pacific Grove Marine Gardens",
    location: "Monterey County",
    coordinates: { lat:  36.640000, lng: -121.920000 },
    region: "Central Coast",
    description:
      "State Marine Conservation Area with granitic reefs. Giant kelp and bull kelp co-occur with high biodiversity.",
    metrics: {
      historicalPresence: 92,
      sstSuitability: 85,
      nutrientAvailability: 88,
      depthSuitability: 88,
      urchinDensityRisk: 72,
      waveExposure: 70,
      proximityToKelp: 94,
      waterClarity: 82,
      siteAccessibility: 90,
    },
    riskFlags: [],
  },
  { 
    id: "monterey-bay-south",
    name: "Monterey Bay - South Shore",
    location: "Monterey County",
    coordinates: { lat: 36.500000, lng: -121.980000 },
    region: "Central Coast",
    description:
      "Prime kelp habitat in the Monterey Bay National Marine Sanctuary. Strong upwelling canyon provides consistent nutrients.",
    metrics: {
      historicalPresence: 95,
      sstSuitability: 86,
      nutrientAvailability: 92,
      depthSuitability: 90,
      urchinDensityRisk: 48,
      waveExposure: 72,
      proximityToKelp: 96,
      waterClarity: 80,
      siteAccessibility: 85,
    },
    riskFlags: [
      { type: "high", label: "Urchin barren encroachment" },
    ],
  },
  {  
    id: "carmel-bay",
    name: "Carmel Bay",
    location: "Monterey County",
    coordinates: { lat: 36.550000, lng: -121.940000 },
    region: "Central Coast",
    description:
      "Granite-bottomed bay within Point Lobos SMCA. Excellent water clarity and moderate wave protection from Point Lobos headland.",
    metrics: {
      historicalPresence: 90,
      sstSuitability: 84,
      nutrientAvailability: 85,
      depthSuitability: 86,
      urchinDensityRisk: 68,
      waveExposure: 74,
      proximityToKelp: 90,
      waterClarity: 88,
      siteAccessibility: 82,
    },
    riskFlags: [],
  },
  {
    id: "big-sur-north",
    name: "Big Sur - Andrew Molera",
    location: "Monterey County",
    coordinates: { lat: 36.2846, lng: -121.8453 },
    region: "Central Coast",
    description:
      "Remote rocky coastline with limited human disturbance. Strong upwelling and deep rocky substrate support robust kelp attachment.",
    metrics: {
      historicalPresence: 80,
      sstSuitability: 82,
      nutrientAvailability: 87,
      depthSuitability: 74,
      urchinDensityRisk: 75,
      waveExposure: 45,
      proximityToKelp: 70,
      waterClarity: 78,
      siteAccessibility: 35,
    },
    riskFlags: [
      { type: "medium", label: "High wave energy" },
      { type: "low", label: "Low human disturbance" },
    ],
  },
  {
    id: "san-simeon",
    name: "San Simeon Cove",
    location: "San Luis Obispo County",
    coordinates: { lat: 35.6433, lng: -121.1897 },
    region: "Central Coast",
    description:
      "Protected cove with kelp-dependent marine mammal populations. Moderate depth with good substrate for kelp holdfast attachment.",
    metrics: {
      historicalPresence: 76,
      sstSuitability: 78,
      nutrientAvailability: 74,
      depthSuitability: 82,
      urchinDensityRisk: 70,
      waveExposure: 76,
      proximityToKelp: 68,
      waterClarity: 75,
      siteAccessibility: 60,
    },
    riskFlags: [],
  },
  {
    id: "cambria",
    name: "Cambria - San Simeon Reef",
    location: "San Luis Obispo County",
    coordinates: { lat: 35.5642, lng: -121.1060 },
    region: "Central Coast",
    description:
      "Offshore rocky reef complex with historical giant kelp canopy. Transition zone between cooler north and warmer south waters.",
    metrics: {
      historicalPresence: 72,
      sstSuitability: 75,
      nutrientAvailability: 70,
      depthSuitability: 80,
      urchinDensityRisk: 65,
      waveExposure: 64,
      proximityToKelp: 60,
      waterClarity: 72,
      siteAccessibility: 52,
    },
    riskFlags: [
      { type: "medium", label: "Warming trend in SST" },
    ],
  },
  {
    id: "morro-bay",
    name: "Morro Bay - Estero Bluffs",
    location: "San Luis Obispo County",
    coordinates: { lat: 35.3711, lng: -120.8580 },
    region: "Central Coast",
    description:
      "Near estuary outflow with elevated nutrient levels. Rocky substrate within the Morro Bay National Estuary boundary.",
    metrics: {
      historicalPresence: 68,
      sstSuitability: 73,
      nutrientAvailability: 80,
      depthSuitability: 76,
      urchinDensityRisk: 78,
      waveExposure: 70,
      proximityToKelp: 55,
      waterClarity: 60,
      siteAccessibility: 78,
    },
    riskFlags: [
      { type: "medium", label: "Sediment plume from estuary" },
    ],
  },

  // ─── SOUTH COAST (Warmer SSTs, lower nutrients, better wave protection) ───
  {
    id: "santa-barbara",
    name: "Santa Barbara - Arroyo Burro",
    location: "Santa Barbara County",
    coordinates: { lat: 34.4028, lng: -119.7443 },
    region: "South Coast",
    description:
      "South-facing coastline in the Santa Barbara Channel. Giant kelp historically dominant with moderate seasonal variability.",
    metrics: {
      historicalPresence: 84,
      sstSuitability: 68,
      nutrientAvailability: 65,
      depthSuitability: 82,
      urchinDensityRisk: 62,
      waveExposure: 78,
      proximityToKelp: 80,
      waterClarity: 76,
      siteAccessibility: 92,
    },
    riskFlags: [
      { type: "medium", label: "Warming SST trend" },
    ],
  },
  {
    id: "channel-islands",
    name: "Channel Islands - Anacapa",
    location: "Ventura County",
    coordinates: { lat: 34.0130, lng: -119.3640 },
    region: "South Coast",
    description:
      "National Marine Sanctuary island with exceptional kelp habitat. Cold upwelling on north-facing shores provides nutrient-rich conditions.",
    metrics: {
      historicalPresence: 91,
      sstSuitability: 80,
      nutrientAvailability: 78,
      depthSuitability: 85,
      urchinDensityRisk: 55,
      waveExposure: 65,
      proximityToKelp: 88,
      waterClarity: 85,
      siteAccessibility: 45,
    },
    riskFlags: [
      { type: "medium", label: "Urchin population increasing" },
    ],
  },
  {
    id: "palos-verdes",
    name: "Palos Verdes Peninsula",
    location: "Los Angeles County",
    coordinates: { lat: 33.7456, lng: -118.3903 },
    region: "South Coast",
    description:
      "Rocky peninsula with recovering kelp forests. Recent restoration efforts by The Bay Foundation show promising regrowth.",
    metrics: {
      historicalPresence: 70,
      sstSuitability: 62,
      nutrientAvailability: 58,
      depthSuitability: 78,
      urchinDensityRisk: 50,
      waveExposure: 72,
      proximityToKelp: 75,
      waterClarity: 68,
      siteAccessibility: 85,
    },
    riskFlags: [
      { type: "medium", label: "Urban runoff" },
      { type: "high", label: "Urchin barren present" },
    ],
  },
  {
    id: "laguna-beach",
    name: "Laguna Beach - Crystal Cove",
    location: "Orange County",
    coordinates: { lat: 33.5742, lng: -117.8400 },
    region: "South Coast",
    description:
      "State Marine Conservation Area with underwater park. Rocky reefs at moderate depth with seasonal kelp canopy.",
    metrics: {
      historicalPresence: 65,
      sstSuitability: 58,
      nutrientAvailability: 52,
      depthSuitability: 74,
      urchinDensityRisk: 60,
      waveExposure: 80,
      proximityToKelp: 70,
      waterClarity: 74,
      siteAccessibility: 88,
    },
    riskFlags: [
      { type: "high", label: "Elevated SST" },
    ],
  },
  {
    id: "la-jolla",
    name: "La Jolla - Scripps Coastal Reserve",
    location: "San Diego County",
    coordinates: { lat: 32.8662, lng: -117.2544 },
    region: "South Coast",
    description:
      "Adjacent to Scripps Institution of Oceanography. Long-term monitoring dataset available. Giant kelp with seasonal die-back patterns.",
    metrics: {
      historicalPresence: 78,
      sstSuitability: 60,
      nutrientAvailability: 55,
      depthSuitability: 80,
      urchinDensityRisk: 65,
      waveExposure: 76,
      proximityToKelp: 82,
      waterClarity: 78,
      siteAccessibility: 90,
    },
    riskFlags: [
      { type: "medium", label: "Seasonal SST spikes" },
    ],
  },
  {
    id: "point-loma",
    name: "Point Loma Kelp Forest",
    location: "San Diego County",
    coordinates: { lat: 32.6734, lng: -117.2426 },
    region: "South Coast",
    description:
      "One of Southern California\u2019s most studied kelp forests. Large contiguous reef system with decades of monitoring data from SDSU and NOAA.",
    metrics: {
      historicalPresence: 88,
      sstSuitability: 64,
      nutrientAvailability: 62,
      depthSuitability: 84,
      urchinDensityRisk: 58,
      waveExposure: 74,
      proximityToKelp: 92,
      waterClarity: 80,
      siteAccessibility: 82,
    },
    riskFlags: [
      { type: "medium", label: "Warming trend" },
      { type: "low", label: "Strong monitoring program" },
    ],
  },
];
